---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: essi
resources:
  - ../../base/v1

patches:
  - target:
      kind: Ingress
      name: portfolio-ingress
    path: patches-ingress.yaml
