- op: replace
  path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
  value: essiantola.com
- op: replace
  path: /spec/rules/0/host
  value: essiantola.com
- op: replace
  path: /spec/tls/0/hosts/0
  value: essiantola.com
